### ISSUE TITLE
Wrong More Examples section in README.md

### ISSUE THREAD

**Issue by pozabil** [igorkasyanchuk/active_storage_validations#200]
https://github.com/igorkasyanchuk/active_storage_validations#more-examples
`- Content type validation using symbols. In order to infer the correct mime type from the symbol, the types must be registered with Marcel::EXTENSIONS (MimeMagic::EXTENSIONS for Rails <= 6.1.3).`
However, the description is incorrect, because `marcel` gem uses in all the latest stable versions:
`Late Friday, Rails 5.2.5, 6.0.3.6 and 6.1.3.1 were posted with a revised version of its Active Storage service that replaces its mimemagic dependency with Marcel 1.0.0.`
And also, `marcel` gem is included in the dependencies now.

**Comment by Mth0158** [comment]
Hi @pozabil,
Thanks for raising this issue.
As I understand it, this line is a warning for those who did not update their Rails versions to `5.2.5`, `6.0.3.6` or `6.1.3.1`, they should use the registered types used in [`MimeMagic::EXTENSIONS`](https://github.com/mimemagicrb/mimemagic/blob/master/lib/mimemagic/tables.rb) (or [`Marcel::EXTENSIONS`](https://github.com/rails/marcel/blob/main/lib/marcel/tables.rb) for those who updated).

To me it's okay till this point. However, we do not use `MimeMagic` gem to check the content types anymore, we only use `Marcel` [here](https://github.com/igorkasyanchuk/active_storage_validations/blob/master/lib/active_storage_validations/content_type_validator.rb#L40C5-L40C5.).

So, from what I understand, we should either:
- Conditionally use `Marcel` or `MimeMagic` based on Rails gem version
- Remove support from `MimeMagic` by removing it from the [README](https://github.com/igorkasyanchuk/active_storage_validations/blob/master/README.md) and from the gemfiles.lock ([6.1](https://github.com/igorkasyanchuk/active_storage_validations/blob/master/gemfiles/rails_6_1.gemfile.lock) and [global](https://github.com/igorkasyanchuk/active_storage_validations/blob/master/Gemfile.lock)) => meaning we should at least update our Rails 6.1.0 [`gemfile`](https://github.com/igorkasyanchuk/active_storage_validations/blob/master/gemfiles/rails_6_1.gemfile) to a higher version, to `6.1.7` for example (released more than 1 year ago) 

Maybe we could also change the `must be registered with` formulation by `must be registered using`, it feels a bit easier to understand to me

@igorkasyanchuk what do you think? I'll go for upgrading our Rails 6.1.0 gemfile since `MimeMagic` is only used by Rails < 6.1.3.1 versions which has been released 2 years and half ago + Rails 6.1 is reaching EOL in 6 months (https://endoflife.date/rails)
