### ISSUE TITLE
content type validation

### ISSUE THREAD

**Issue by Piioo** [igorkasyanchuk/active_storage_validations#309]
We try to update from version 1.3.0 to 1.3.4 and our validations are broken now, because the content type validation is changed.

In our Specs we has something like this

```
    # here we attach already the file with correct content type
    let(:document) { FactoryBot.build(:insurance_document) }

    it 'is not valid with wrong file type' do
      document.file.blob.content_type = 'wrong/filetype'
      expect(document).to be_invalid
    end
```

This test was green in version 1.3.0 but now it is red, because its valid.

But the validation works correct when the file is attached, so maybe it is only a low problem

**Comment by Mth0158** [comment]
Hi @Piioo 
Thanks for raising the issue. Can you provide us the model validation + the built field in your factory?

**Comment by Piioo** [comment]
```
FactoryBot.define do
  factory :insurance_document, class: 'Document' do
    description { Faker::Beer.hop }

    after(:build) do |document|
      document.file.attach(
        io: Rails.root.join('spec/fixtures/files/blank.pdf').open,
        filename: 'blank.pdf',
        content_type: 'application/pdf'
      )
    end
  end
end
```

```
class Document < ApplicationRecord
  has_one_attached :file, service: :s3

  ALLOWED_FILE_TYPES = %w[application/pdf].freeze

  validates :file, attached: true, content_type: ALLOWED_FILE_TYPES
end
```

**Comment by Mth0158** [comment]
Hi @Piioo,
Thanks for providing additional context. The issue is that we changed our way of validating content_type a bit (changed from all attached files from only new files attached). This is the same is 99% of the cases.
This is the 1% case, you are changing the content_type of the `document.file.blob`, but when the validation is being done, it's performed on the attachment (`{ io: ..., filename: ..., content_type: ... }` here).
Instead, try to update the value of the attachment rather than the blob

**Comment by Mth0158** [comment]
@Piioo did it fixed your issue? :)

**Comment by Piioo** [comment]
@Mth0158 yes thanks
